name:                faewyld
version:             0.1.0.0
github:              "githubuser/gsc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gsc#readme>

dependencies:
- base >= 4.7 && < 5
# REST Web Server and utilities
- servant
- servant-server
- servant-blaze
- blaze-html
- blaze-markup
- aeson
- text
- wai
- warp
# Websocket Web Server
- servant-websockets
- transformers
- websockets
- containers
- butter

library:
  source-dirs: src

executables:
  faewyld:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - faewyld

tests:
  gsc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - faewyld
